name: Build StormHvH DLL

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile All Files to StormHvH DLL
      run: |
        cl.exe /LD /O2 /EHsc /std:c++17 *.cpp /link /OUT:stormhvh.dll user32.lib kernel32.lib gdi32.lib winmm.lib
        
    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StormHvH-15MB-DLL
        path: stormhvh.dll
